services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-web-app
    ports:
      - "9091:9091"
    environment:
#      - MODE=prod
      - GPGPS_apiURL=${GPGPS_apiURL}
      - GPGPS_authorization=${GPGPS_authorization}
      - GPGPS_asaaseUser=${GPGPS_asaaseUser}
      - GPGPS_languageCode=${GPGPS_languageCode}
      - GPGPS_language=${GPGPS_language}
      - GPGPS_deviceId=${GPGPS_deviceId}
      - GPGPS_androidCert=${GPGPS_androidCert}
      - GPGPS_androidPackage=${GPGPS_androidPackage}
      - GPGPS_countryName=${GPGPS_countryName}
      - GPGPS_country=${GPGPS_country}
      - PORT=${PORT}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
